"""Initial migration.

Revision ID: a16bfeaba26d
Revises: 
Create Date: 2022-11-30 02:43:52.987817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16bfeaba26d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('start_location', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('end_location', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('miles', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entry_pkey')
    )
    # ### end Alembic commands ###
